# This workflow will install Python dependencies, run tests and lint with a single version of Python
#Still working on it
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: setup-chromedriver
    - uses: nanasess/setup-chromedriver@v1.0.1
    - name: Install dependencies
      run: |
        shell: python
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install mysql-connector-python
        pip install selenium
        pip install pyttsx3
        pip install wikipedia
    - name: flake8 Lint
    - uses: py-actions/flake8@v1
    - name: Test with pytest
      run: |
        pytest
